//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код был создан программным средством.
//
//     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
//     код создается повторно. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba3 {
    
    
    public partial class NewTicket {
        
        /// <summary>
        /// Элемент управления ErrorMessage.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ErrorMessage;
        
        /// <summary>
        /// Элемент управления ErrorMessageText.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ErrorMessageText;
        
        /// <summary>
        /// Элемент управления TicketName.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TicketName;
        
        /// <summary>
        /// Элемент управления TicketDescription.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TicketDescription;
        
        /// <summary>
        /// Элемент управления TicketCategory.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList TicketCategory;
    }
} 